//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatureMonster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creature
    {
        public int Id { get; set; }
        public int Id_body { get; set; }
        public int Id_tail { get; set; }
        public int Id_head { get; set; }
        public int Id_legs { get; set; }
        public string Name_creature { get; set; }
        public byte[] Photo { get; set; }
        public int Id_authorization { get; set; }
    
        public virtual Authorization Authorization { get; set; }
        public virtual Body Body { get; set; }
        public virtual Head Head { get; set; }
        public virtual Legs Legs { get; set; }
        public virtual Tail Tail { get; set; }
    }
}
