//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatureMonster.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user24Entities : DbContext
    {
        public user24Entities()
            : base("name=user24Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Body> Body { get; set; }
        public virtual DbSet<Creature> Creature { get; set; }
        public virtual DbSet<Head> Head { get; set; }
        public virtual DbSet<Legs> Legs { get; set; }
        public virtual DbSet<Tail> Tail { get; set; }
        public virtual DbSet<Type_legs> Type_legs { get; set; }
        public virtual DbSet<Type_tail> Type_tail { get; set; }
        public virtual DbSet<TypeHead> TypeHead { get; set; }
    }
}
