//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatureMonster.Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tail()
        {
            this.Creature = new HashSet<Creature>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Photo { get; set; }
        public int IdType_tail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Creature> Creature { get; set; }
        public virtual TypeTail TypeTail { get; set; }
    }
}
